#!/bin/bash

# Use this to connect to the MySQL container with an interactive session

docker run \
    --interactive \
    --tty \
    --link address-book-mysql:mysql \
    --rm \
    mysql \
        sh -c \
            'exec mysql \
                -h"$MYSQL_PORT_3306_TCP_ADDR" \
                -P"$MYSQL_PORT_3306_TCP_PORT" \
                -uroot \
                -p"$MYSQL_ENV_MYSQL_ROOT_PASSWORD"'
